

# homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - google-chrome
  - sublime-text
  - powershell
  - raspberry-pi-imager
  - orcaslicer
  - claude
  - visual-studio-code
  - github
  - intellij-idea
  - yubico-authenticator
  - postman
  - wireshark
  - microsoft-office
  - 1password-cli

homebrew_installed_packages:
  - git
  - openssl
  - wget
  - curl
  - ansible
  - python

homebrew_upgrade_all_packages: true

# See `geerlingguy.mac.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 443987910, name: "1Password" }
# Leave these empty for security, sign into app store manually before running
mas_email: ""
mas_password: ""

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
